export const Industries  = [
    { name :"technology"},
    { name :"education"},
    { name :"health care"},
    { name :"blogger"},
    { name :"banking"},
    { name :"wedding"},
    { name :"music"},
    { name :"technologies"},
    { name :"it securities"},
    { name :"parenting"},
    { name :"physiotherphy"},
    { name :"industry tools"},
    { name :"corporate gifting"},
    { name :"mobile retail"},
    { name :"fantasy sports"},
    { name :"digital marketing"},
    { name :"tele communication"},
    { name :"real estate & construction"},
    { name :"legal"},
    { name :"consumer electronics"},
    { name :"food & beverages"},
    { name :"diet & nutrionist"},
    { name :"trading & stock market"},
    { name :"storage & warehousing"},
  ]
