export const portfolio=[
    {"img":"https://i.postimg.cc/s2ybcPrJ/Project6.png"},
    {"img":"https://i.postimg.cc/x8W4bM5M/Project1.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},
    {"img":"https://i.postimg.cc/L6DySdKj/Project2.png"},   
]