export const thread = [
    {
        "img":"https://i.postimg.cc/8CVjwjpf/Group-427319775.png",
        "class":"vertline1"
    },
    {
        "img":"https://i.postimg.cc/3J8QTG1F/Group-427319792-1.png",
        "class":"vertline2"
    },
    {
        "img":"https://i.postimg.cc/6Q35Mns3/Group-427319819.png",
        "class":"vertline3"
    },
    {
        "img":"https://i.postimg.cc/MZYnWy7s/download-1-2-1.png",
        "class":"vertline4"
    },
    {
        "img":"https://i.postimg.cc/FFSxGnQY/Group-427319820-1.png",
        "class":"vertline5"
    },
    {
        "img":"https://i.postimg.cc/CMH5LF4w/download-5-2.png",
        "class":"vertline6"
    },
    {
        "img":"https://i.postimg.cc/kgyvQ39C/Frame-272.png",
        "class":"vertline7"
    },
    {
        "img":"https://i.postimg.cc/W356qQR3/Group-427319821.png",
        "class":"vertline8"
    },
    {
        "img":"https://i.postimg.cc/25z0qdq0/Group-427319822.png",
        "class":"vertline9"
    },
    {
        "img":"https://i.postimg.cc/Ssx87Jd7/download.png",
        "class":"vertline10"
    },
    {
        "img":"https://i.postimg.cc/zB778stp/Group-427319823.png",
        "class":"vertline11"
    },
    {
        "img":"https://i.postimg.cc/kGjTF0WD/Group-427319775-1.png",
        "class":"vertline12"
    },
    {
        "img":"https://i.postimg.cc/jqQ0J29k/Group-427319824.png",
        "class":"vertline13"
    },
   
]